import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { getPokemonList } from "@/utils/pokeapi";

import type { PokemonListType } from "@/utils/types";
import type { GetStaticProps, NextPage } from "next";

type Props = {
  data: PokemonListType;
};

const Home: NextPage<Props> = ({ data }) => {
  const items = data.results.map(({ name }) => (
    <Link key={name} href={`/pokemon/${name}`} passHref>
      <a>{name}</a>
    </Link>
  ));

  return (
    <div className="flex min-h-screen flex-col items-center justify-center py-2">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full flex-1 flex-col items-center justify-center px-20 text-center">
        <div className="grid grid-cols-2 gap-4 md:grid-cols-6">{items}</div>
      </main>

      <footer className="flex h-24 w-full items-center justify-center border-t">
        <a
          className="flex items-center justify-center gap-2"
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </a>
      </footer>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const data = await getPokemonList();

  return { props: { data } };
};
